name: Update Coverage Badge

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Generate coverage percentage
        id: coverage
        run: |
          # Extract coverage percentage from lcov.info
          if [ -f "coverage/lcov.info" ]; then
            COVERAGE=$(grep -E "^LF:" coverage/lcov.info | awk -F: '{sum += $2} END {print sum}')
            HITS=$(grep -E "^LH:" coverage/lcov.info | awk -F: '{sum += $2} END {print sum}')
            if [ "$COVERAGE" -gt 0 ]; then
              PERCENTAGE=$((HITS * 100 / COVERAGE))
            else
              PERCENTAGE=0
            fi
          else
            PERCENTAGE=0
          fi
          
          # Determine color based on coverage
          if [ "$PERCENTAGE" -ge 80 ]; then
            COLOR="brightgreen"
          elif [ "$PERCENTAGE" -ge 60 ]; then
            COLOR="yellow"
          else
            COLOR="red"
          fi
          
          echo "coverage=$PERCENTAGE" >> $GITHUB_OUTPUT
          echo "color=$COLOR" >> $GITHUB_OUTPUT
          echo "Coverage: $PERCENTAGE%"

      - name: Update README with coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          # Create badge URL
          BADGE_URL="https://img.shields.io/badge/coverage-${{ steps.coverage.outputs.coverage }}%25-${{ steps.coverage.outputs.color }}?logo=vitest&style=flat"
          
          # Read current README
          README_CONTENT=$(cat README.md)
          
          # Check if coverage badge already exists
          if echo "$README_CONTENT" | grep -q "coverage.*brightgreen\|coverage.*yellow\|coverage.*red"; then
            # Update existing badge
            sed -i 's|https://img.shields.io/badge/coverage-[0-9]*%25-[a-z]*?logo=vitest|'"$BADGE_URL"'|g' README.md
          else
            # Add new badge after the first heading
            sed -i '1a\\n![Test Coverage]('"$BADGE_URL"')\n' README.md
          fi
          
          # Commit changes if any
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "docs: update coverage badge to ${{ steps.coverage.outputs.coverage }}%" || echo "No changes to commit"
            git push || echo "Push failed, but this is not critical"
          fi 